server:
  port: 8889
  error:
    include-stacktrace: NEVER
spring:
  application:
    name: addresses-service
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2.console.enabled: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

